name: ClaimForge CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify TEST.sh exists and is executable
        run: |
          if [[ ! -x TEST.sh ]]; then
            echo "TEST.sh is missing or not executable"
            ls -l TEST.sh || echo "TEST.sh not found"
            chmod +x TEST.sh || true
          fi

      - name: Ensure required test files exist
        run: |
          mkdir -p ./data

          if [[ ! -f .env ]]; then
            echo "Creating dummy .env for CI..."
            echo "GEMINI_API_KEY=ci_dummy_gemini" > .env
            echo "GOOGLE_API_KEY=ci_dummy_google" >> .env
            echo "SERP_API_KEY=ci_dummy_serp" >> .env
          fi

          if [[ ! -f ./data/invention_disclosure.txt ]]; then
            echo "Creating dummy invention_disclosure.txt for CI..."
            echo "Placeholder test disclosure" > ./data/invention_disclosure.txt
          fi

      - name: Run smoke test
        run: bash TEST.sh

